[package]
name = "s3core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
time.workspace = true
crc32fast = "1"
mime_guess = "2"
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-sdk-sts.workspace = true
aws-sdk-sso.workspace = true
aws-sdk-ssooidc.workspace = true
aws-credential-types.workspace = true
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
